# Generated by Django 5.1.4 on 2025-01-14 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_type',
            field=models.CharField(choices=[('PER', 'PERMANENT'), ('INTR', 'INTERN')], default='INTR', max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
